[package]
name = "const_sv2"
version = "0.1.0"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "Sv2  constatnts"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#[dev-dependencies]
#cbindgen = "0.16.0"
