[package]
name = "binary_codec_sv2"
version = "0.1.1"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "Sv2 data format"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
no_std = []
deafult = ["no_std"]
